"""Render recorded episodes (demos from collect, rollouts from evaluate --record) to MP4.

Every stack_bc zarr stores the full MuJoCo qpos per 10 Hz tick (arm, all 6 gripper joints, cube
free joints), so an episode can be replayed kinematically in the offline-built scene - no sim, no
ROS, any camera. Ticks are interpolated to --fps for smooth playback (joints linearly, cube
orientations by normalized quaternion lerp).

  python3 -m stack_bc.replay --dataset /tmp/rollout.zarr --episode 0 --out /tmp/rollout0.mp4
  # side by side: left = --dataset/--episode, right = --compare DATASET EPISODE
  python3 -m stack_bc.replay --dataset /tmp/rollout.zarr --episode 0 \\
      --compare ~/data/stack_bc/overfit.zarr 0 --out /tmp/rollout0_vs_demo.mp4

The scene comes from stack_bc.scene (built on first use into ~/.cache/stack_bc/scene); it is
generated by the same steps as the live launch file, so qpos layouts match.
"""

import argparse
import os

import numpy as np
import zarr

os.environ.setdefault("MUJOCO_GL", "egl")  # offscreen GPU rendering, no window needed
import mujoco  # noqa: E402  (must follow MUJOCO_GL)

from stack_bc.scene import DEFAULT_OUT  # noqa: E402

# Overview camera: from beyond the far edge of the table looking back toward the robot, so the
# cubes and gripper stay in front of the arm (MuJoCo free camera: azimuth 0 looks along +x).
CAMERA = dict(lookat=(-0.48, 0.0, 0.36), distance=0.95, azimuth=20.0, elevation=-32.0)


def load_episode(path, episode):
    root = zarr.open(os.path.expanduser(path), "r")
    ends = root["meta/episode_ends"][:]
    if not 0 <= episode < len(ends):
        raise ValueError(f"{path}: episode {episode} out of range (has {len(ends)})")
    start = 0 if episode == 0 else int(ends[episode - 1])
    return root["data/qpos"][start:int(ends[episode])]


def upsample(qpos, model, factor):
    """Interpolate 10 Hz qpos rows to factor x the rate; free-joint quaternions are nlerp'ed."""
    free_quat_adr = [model.jnt_qposadr[j] + 3 for j in range(model.njnt)
                     if model.jnt_type[j] == mujoco.mjtJoint.mjJNT_FREE]
    out = []
    for a, b in zip(qpos[:-1], qpos[1:]):
        for k in range(factor):
            s = k / factor
            q = (1 - s) * a + s * b
            for adr in free_quat_adr:
                qa, qb = a[adr:adr + 4], b[adr:adr + 4]
                if np.dot(qa, qb) < 0:
                    qb = -qb
                qi = (1 - s) * qa + s * qb
                q[adr:adr + 4] = qi / np.linalg.norm(qi)
            out.append(q)
    out.append(qpos[-1])
    return np.array(out)


def render(model, qpos_rows, width, height):
    data = mujoco.MjData(model)
    cam = mujoco.MjvCamera()
    cam.type = mujoco.mjtCamera.mjCAMERA_FREE
    cam.lookat[:] = CAMERA["lookat"]
    cam.distance, cam.azimuth, cam.elevation = CAMERA["distance"], CAMERA["azimuth"], CAMERA["elevation"]
    with mujoco.Renderer(model, height=height, width=width) as renderer:
        for q in qpos_rows:
            data.qpos[:] = q
            mujoco.mj_forward(model, data)
            renderer.update_scene(data, camera=cam)
            yield renderer.render()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--episode", type=int, default=0)
    parser.add_argument("--compare", nargs=2, metavar=("DATASET", "EPISODE"), default=None,
                        help="render a second episode to the right, frame-synchronized")
    parser.add_argument("--out", required=True, help="output .mp4")
    parser.add_argument("--fps", type=int, default=30, help="multiple of the 10 Hz recording rate")
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--scene", default=DEFAULT_OUT, help="offline scene dir (built if missing)")
    args = parser.parse_args()
    import imageio.v2 as imageio

    scene_xml = os.path.join(os.path.expanduser(args.scene), "scene.xml")
    if not os.path.exists(scene_xml):
        from stack_bc.scene import build_scene
        scene_xml = build_scene(os.path.expanduser(args.scene))
    model = mujoco.MjModel.from_xml_path(scene_xml)

    factor = max(1, round(args.fps / 10))
    episodes = [load_episode(args.dataset, args.episode)]
    if args.compare:
        episodes.append(load_episode(args.compare[0], int(args.compare[1])))
    for q in episodes:
        if q.shape[1] != model.nq:
            raise ValueError(f"recorded qpos has {q.shape[1]} values, scene has nq={model.nq} - different scene?")
    # Pad the shorter episode with its final state so both panels run the same length.
    n = max(len(q) for q in episodes)
    episodes = [np.vstack([q, np.repeat(q[-1:], n - len(q), axis=0)]) for q in episodes]
    streams = [render(model, upsample(q, model, factor), args.width, args.height) for q in episodes]

    out = os.path.expanduser(args.out)
    with imageio.get_writer(out, fps=10 * factor, codec="libx264", quality=8, macro_block_size=8) as writer:
        for frames in zip(*streams):
            writer.append_data(np.hstack(frames))
    print(f"wrote {out}: {n} ticks ({n / 10:.1f} s) at {10 * factor} fps"
          + (" | left: --dataset, right: --compare" if args.compare else ""))


if __name__ == "__main__":
    main()
